version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel_app
        volumes:
            - ./:/var/www/html
        ports:
            - 8000:9000
        networks:
            - laravel_network

    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - laravel_network

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        networks:
            - laravel_network

volumes:
    db_data:

networks:
    laravel_network:
